
# PLEASE NOTE:
#  This .py file is not longer in use.  All smartbody initialization is now done within Unity itself.  See the SmartbodyManager gameobject
#
#


print "loading init-unity-sbm.py"

scene.setScale(1.0)
scene.command("path audio .")
scene.addAssetPath("ME", "Art/Characters/SB/ChrBrad")
scene.addAssetPath("ME", "Art/Characters/SB/ChrRachel")
scene.addAssetPath("ME", "Art/Characters/SB/ChrUtah")
scene.addAssetPath("ME", "Art/Characters/SB/common-sk")
scene.loadAssets()


scene.run("zebra2-map.py")
scene.command("skeletonmap ChrBrad.sk zebra2")
scene.command("skeletonmap ChrRachel.sk zebra2")
scene.command("motionmapdir Art/Characters/SB/ChrBrad zebra2")


defaultFace = scene.getFaceDefinition("_default_")
defaultFace.setFaceNeutral("face_neutral")

defaultFace.setAU(1,  "left",  "fac_1L_inner_brow_raiser")
defaultFace.setAU(1,  "right", "fac_1R_inner_brow_raiser")
defaultFace.setAU(2,  "left",  "fac_2L_outer_brow_raiser")
defaultFace.setAU(2,  "right", "fac_2R_outer_brow_raiser")
defaultFace.setAU(4,  "left",  "fac_4L_brow_lowerer")
defaultFace.setAU(4,  "right", "fac_4R_brow_lowerer")
defaultFace.setAU(5,  "both",  "fac_5_upper_lid_raiser")
defaultFace.setAU(6,  "both",  "fac_6_cheek_raiser")
defaultFace.setAU(7,  "both",  "fac_7_lid_tightener")
defaultFace.setAU(9,  "both",  "fac_9_nose_wrinkler")
defaultFace.setAU(10, "both",  "fac_10_upper_lip_raiser")
defaultFace.setAU(12, "both",  "fac_12_lip_corner_puller")
defaultFace.setAU(15, "both",  "fac_15_lip_corner_depressor")
defaultFace.setAU(20, "both",  "fac_20_lip_stretcher")
defaultFace.setAU(23, "both",  "fac_23_lip_tightener")
defaultFace.setAU(25, "both",  "fac_25_lips_part")
defaultFace.setAU(26, "both",  "fac_26_jaw_drop")
defaultFace.setAU(27, "both",  "fac_27_mouth_stretch")
defaultFace.setAU(38, "both",  "fac_38_nostril_dilator")
defaultFace.setAU(39, "both",  "fac_39_nostril_compressor")
defaultFace.setAU(45, "left",  "fac_45L_blink")
defaultFace.setAU(45, "right", "fac_45R_blink")

defaultFace.setViseme("Ao",  "viseme_ao")
defaultFace.setViseme("D",   "viseme_d")
defaultFace.setViseme("EE",  "viseme_ee")
defaultFace.setViseme("Er",  "viseme_er")
defaultFace.setViseme("f",   "viseme_f")
defaultFace.setViseme("j",   "viseme_j")
defaultFace.setViseme("KG",  "viseme_kg")
defaultFace.setViseme("Ih",  "viseme_ih")
defaultFace.setViseme("NG",  "viseme_ng")
defaultFace.setViseme("Oh",  "viseme_oh")
defaultFace.setViseme("OO",  "viseme_oo")
defaultFace.setViseme("R",   "viseme_r")
defaultFace.setViseme("Th",  "viseme_th")
defaultFace.setViseme("Z",   "viseme_z")
defaultFace.setViseme("BMP", "viseme_bmp")
defaultFace.setViseme("blink", "fac_45_blink")


chrBradFace = scene.createFaceDefinition("ChrBradFace")
chrBradFace.setFaceNeutral("ChrBrad@face_neutral")

chrBradFace.setViseme("open",    "ChrBrad@open")
chrBradFace.setViseme("W",       "ChrBrad@W")
chrBradFace.setViseme("ShCh",    "ChrBrad@ShCh")
chrBradFace.setViseme("PBM",     "ChrBrad@PBM")
chrBradFace.setViseme("FV",      "ChrBrad@FV")
chrBradFace.setViseme("wide",    "ChrBrad@wide")
chrBradFace.setViseme("tBack",   "ChrBrad@tBack")
chrBradFace.setViseme("tRoof",   "ChrBrad@tRoof")
chrBradFace.setViseme("tTeeth",  "ChrBrad@tTeeth")

#chrBradFace.setAU(1,  "both",    "ChrBrad@001_inner_brow_raiser")
chrBradFace.setAU(1,  "left",    "ChrBrad@001_inner_brow_raiser_lf")
chrBradFace.setAU(1,  "right",   "ChrBrad@001_inner_brow_raiser_rt")
#chrBradFace.setAU(2,  "both",    "ChrBrad@002_outer_brow_raiser")
chrBradFace.setAU(2,  "left",    "ChrBrad@002_outer_brow_raiser_lf")
chrBradFace.setAU(2,  "right",   "ChrBrad@002_outer_brow_raiser_rt")
#chrBradFace.setAU(4,  "both",    "ChrBrad@004_brow_lowerer")
chrBradFace.setAU(4,  "left",    "ChrBrad@004_brow_lowerer_lf")
chrBradFace.setAU(4,  "right",   "ChrBrad@004_brow_lowerer_rt")
chrBradFace.setAU(5,  "both",    "ChrBrad@005_upper_lid_raiser")
chrBradFace.setAU(6,  "both",    "ChrBrad@006_cheek_raiser")
chrBradFace.setAU(7,  "both",    "ChrBrad@007_lid_tightener")
#chrBradFace.setAU(9,  "both",    "ChrBrad@009_nose_wrinkle")
chrBradFace.setAU(10, "both",    "ChrBrad@010_upper_lip_raiser")
#chrBradFace.setAU(12, "both",    "ChrBrad@012_lip_corner_puller")
chrBradFace.setAU(12, "left",    "ChrBrad@012_lip_corner_puller_lf")
chrBradFace.setAU(12, "right",   "ChrBrad@012_lip_corner_puller_rt")
#chrBradFace.setAU(15, "both",    "ChrBrad@015_lip_corner_depressor")
#chrBradFace.setAU(23, "both",    "ChrBrad@023_lip_tightener")
chrBradFace.setAU(25, "both",    "ChrBrad@025_lips_part")
chrBradFace.setAU(26, "both",    "ChrBrad@026_jaw_drop")
#chrBradFace.setAU(27, "both",    "ChrBrad@027_mouth_stretch")
#chrBradFace.setAU(38, "both",    "ChrBrad@038_nostril_dilator")
#chrBradFace.setAU(45, "both",    "ChrBrad@blink")
chrBradFace.setAU(45, "left",    "ChrBrad@045_blink_lf")
chrBradFace.setAU(45, "right",   "ChrBrad@045_blink_rt")
